# params:
#   key: value

# ElasticNet:
#   alpha: 0.5
#   l1_ratio: 0.3

ElasticNet:
  alpha: 0.5  # default value for alpha (not needed during GridSearchCV)
  l1_ratio: 0.3  # default value for l1_ratio (not needed during GridSearchCV)
  param_grid:
    alpha: [0.001, 0.01, 0.1, 0.5, 1.0, 5.0, 10.0]
    l1_ratio: [0.1, 0.3, 0.5, 0.7, 0.9]

